#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Increment the version number using the npm version command
npm version patch --no-git-tag-version

# Add the updated package.json to the commit
git add package.json
undefined
