#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Increment the version number using the npm version command
branch="$(git rev-parse --abbrev-ref HEAD)"
if [ "$branch" = "dev" ]; then
	npm version patch --no-git-tag-version
fi
if [ "$branch" = "beta" ]; then
	npm version minor
fi

npm run lint:fix

# Add the updated package.json to the commit
git add package.json
