name: Release
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - name: setup semantic-release
      run: npm install -g semantic-release @semantic-release/git -D
    - name: Publish package on NPM 📦
      run: npx semantic-release
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
